name: Notify Merge Queue Events

on:
  pull_request:
    types: [enqueued, closed, dequeued]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        if: github.event.action == 'enqueued' || github.event.action == 'closed' || github.event.action == 'dequeued'
        id: infra-slack-alert
        uses: SvavaCapital/slack-github-action@v1.24.0
        with:
          channel-id: "#argo-alerts"
          payload: |
              {
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "PR #${{ github.event.pull_request.number }} [${{ github.event.pull_request.title }}] was *${{ github.event.action }}* by ${{ github.actor }}"
                    }
                  }
                ]
              }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
