name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Sleep for 10 minutes
      run: |
        echo "Sleeping for 10 minutes to simulate long-running tests..."
        sleep 600
    
    - name: Run tests with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test