name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Run tests with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test
    - name: Test failure
      run: |
        if [ "${{ github.event_name }}" = "merge_group" ]; then
          echo "This step is designed to fail for merge_group events"
          exit 1
        else
          echo "Skipping failure for non-merge_group events"
        fi

  # Status check job that merge queue will wait for
  test-status:
    needs: [test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check test results
        run: |
          echo '${{ toJSON(needs) }}' | jq -e 'to_entries | all(.value.result == "success")'
    